---
- hosts: 172.31.11.15
  become: yes
  tasks:
    - name: i want to excecute in linux
      command: hostname -f
      register: myresult
    - name: i want of display the first task result 
      debug:
        msg: "{{myresult}}"

    - name: i want to install git
      apt:
        name: git
        state: present
      when: myresult.stderr ==""

    - name: i want to install tree
      apt:
        name: tree
        state: present
        when: myresult.stderr !==""
