---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: "{{myjavapackonubuntu}}"
    apt: 
      name: openjdk-8-jre
      state: present
    when: ansible_os_family =="Debian"

  - name: install java on "RedHat"
    yum:
      name: "{{myjavapackonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"
