---
- hosts: mywebservers
  become: yes
  vars:
    myjavapackonubuntu: "openjdk-8-jre"
    myjavapackonredhat: "openjdk-8-jre"
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{myjavapackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java on RedHat 
    yum:
      name: "openjdk-8-jre"
      state: present
    when: ansible_os_family =="RedHat"
