---
- hosts: all
  become: yes
  tasks:
  - name: install webservers
    apt: 
      name: apache2
      state: present

  - name: Restart service httpd, in all cases
    ansible.builtin.service:
      name: apache2
      state: restarted
